package export

import (
	"fmt"
	"strings"

	"github.com/rafaqwe1/sqlserver-import-export/internal/meta"
	"github.com/rafaqwe1/sqlserver-import-export/internal/sqlfmt"
)

// GenerateSchemaSQL renders the full schema.sql contents: CREATE TABLE
// statements (with inline PK/UNIQUE/CHECK constraints), plain CREATE INDEX
// statements, and finally ALTER TABLE ... ADD CONSTRAINT FOREIGN KEY
// statements for every table, in that order, so table creation never depends
// on cross-table ordering.
func GenerateSchemaSQL(tables []*meta.Table, exportedSet map[string]bool) string {
	var sb strings.Builder

	sb.WriteString("-- Generated by sqlserver-import-export (export mode)\n")
	sb.WriteString("-- Table definitions\n\n")
	for _, t := range tables {
		writeCreateTable(&sb, t)
	}

	sb.WriteString("-- Non-key indexes\n\n")
	for _, t := range tables {
		writeIndexes(&sb, t)
	}

	sb.WriteString("-- Foreign key constraints (added after all tables exist)\n\n")
	writeForeignKeys(&sb, tables, exportedSet)

	return sb.String()
}

func writeCreateTable(sb *strings.Builder, t *meta.Table) {
	fmt.Fprintf(sb, "CREATE TABLE %s (\n", sqlfmt.QuoteQualified(t.Schema, t.Name))

	var lines []string
	for _, c := range t.Columns {
		lines = append(lines, "    "+columnDefLine(c))
	}
	for _, ix := range t.Indexes {
		if ix.IsPrimaryKey || ix.IsUniqueConstraint {
			lines = append(lines, "    "+constraintClause(ix))
		}
	}
	for _, cc := range t.CheckConstraints {
		lines = append(lines, "    "+fmt.Sprintf("CONSTRAINT %s CHECK (%s)", sqlfmt.QuoteIdent(cc.Name), cc.Definition))
	}

	sb.WriteString(strings.Join(lines, ",\n"))
	sb.WriteString("\n);\nGO\n\n")
}

func columnDefLine(c meta.Column) string {
	name := sqlfmt.QuoteIdent(c.Name)

	if c.IsComputed {
		line := fmt.Sprintf("%s AS (%s)", name, c.ComputedDefinition)
		if c.IsPersisted {
			line += " PERSISTED"
			if !c.IsNullable {
				line += " NOT NULL"
			}
		}
		return line
	}

	parts := []string{name, meta.FormatColumnType(c)}
	if meta.IsCharType(c.TypeName) && c.CollationName != "" {
		parts = append(parts, "COLLATE "+c.CollationName)
	}
	if c.IsIdentity {
		parts = append(parts, fmt.Sprintf("IDENTITY(%d,%d)", c.IdentitySeed, c.IdentityIncrement))
	}
	if c.IsNullable {
		parts = append(parts, "NULL")
	} else {
		parts = append(parts, "NOT NULL")
	}
	if c.DefaultConstraintName != "" {
		parts = append(parts, fmt.Sprintf("CONSTRAINT %s DEFAULT %s", sqlfmt.QuoteIdent(c.DefaultConstraintName), c.DefaultDefinition))
	}
	return strings.Join(parts, " ")
}

func constraintClause(ix meta.Index) string {
	kind := "UNIQUE"
	if ix.IsPrimaryKey {
		kind = "PRIMARY KEY"
	}
	clustering := "NONCLUSTERED"
	if ix.IsClustered {
		clustering = "CLUSTERED"
	}
	return fmt.Sprintf("CONSTRAINT %s %s %s (%s)", sqlfmt.QuoteIdent(ix.Name), kind, clustering, keyColumnList(ix))
}

func keyColumnList(ix meta.Index) string {
	cols := ix.KeyColumns()
	parts := make([]string, len(cols))
	for i, c := range cols {
		dir := "ASC"
		if c.IsDescending {
			dir = "DESC"
		}
		parts[i] = fmt.Sprintf("%s %s", sqlfmt.QuoteIdent(c.ColumnName), dir)
	}
	return strings.Join(parts, ", ")
}

func writeIndexes(sb *strings.Builder, t *meta.Table) {
	for _, ix := range t.Indexes {
		if ix.IsPrimaryKey || ix.IsUniqueConstraint {
			continue // rendered inline on CREATE TABLE
		}
		unique := ""
		if ix.IsUnique {
			unique = "UNIQUE "
		}
		clustering := "NONCLUSTERED"
		if ix.IsClustered {
			clustering = "CLUSTERED"
		}
		stmt := fmt.Sprintf("CREATE %s%s INDEX %s ON %s (%s)",
			unique, clustering, sqlfmt.QuoteIdent(ix.Name), sqlfmt.QuoteQualified(t.Schema, t.Name), keyColumnList(ix))

		if inc := ix.IncludedColumns(); len(inc) > 0 {
			names := make([]string, len(inc))
			for i, c := range inc {
				names[i] = sqlfmt.QuoteIdent(c.ColumnName)
			}
			stmt += fmt.Sprintf(" INCLUDE (%s)", strings.Join(names, ", "))
		}
		if ix.FilterDefinition != "" {
			stmt += " WHERE " + ix.FilterDefinition
		}
		sb.WriteString(stmt)
		sb.WriteString(";\nGO\n\n")
	}
}

func writeForeignKeys(sb *strings.Builder, tables []*meta.Table, exportedSet map[string]bool) {
	for _, t := range tables {
		for _, fk := range t.ForeignKeys {
			key := strings.ToLower(fk.RefSchema + "." + fk.RefTable)
			if !exportedSet[key] {
				fmt.Fprintf(sb, "-- Skipped FK %s on %s: referenced table %s.%s is not part of this export\n",
					fk.Name, t.QualifiedName(), fk.RefSchema, fk.RefTable)
				continue
			}

			parentCols := make([]string, len(fk.Columns))
			refCols := make([]string, len(fk.Columns))
			for i, c := range fk.Columns {
				parentCols[i] = sqlfmt.QuoteIdent(c.ParentColumn)
				refCols[i] = sqlfmt.QuoteIdent(c.RefColumn)
			}

			stmt := fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s)",
				sqlfmt.QuoteQualified(t.Schema, t.Name), sqlfmt.QuoteIdent(fk.Name),
				strings.Join(parentCols, ", "),
				sqlfmt.QuoteQualified(fk.RefSchema, fk.RefTable), strings.Join(refCols, ", "))

			if a := foreignKeyActionSQL(fk.DeleteAction); a != "" {
				stmt += " ON DELETE " + a
			}
			if a := foreignKeyActionSQL(fk.UpdateAction); a != "" {
				stmt += " ON UPDATE " + a
			}
			sb.WriteString(stmt)
			sb.WriteString(";\nGO\n\n")
		}
	}
}

func foreignKeyActionSQL(action string) string {
	switch action {
	case "CASCADE":
		return "CASCADE"
	case "SET_NULL":
		return "SET NULL"
	case "SET_DEFAULT":
		return "SET DEFAULT"
	default:
		return ""
	}
}
