package importrun

import (
	"context"
	"database/sql"
	"encoding/hex"
	"fmt"
	"regexp"
	"strconv"
	"strings"
	"time"

	mssql "github.com/microsoft/go-mssqldb"
	"github.com/rafaqwe1/sqlserver-import-export/internal/sqlfmt"
)

// tryBulkInsert attempts to run an INSERT batch (as generated by export mode)
// through SQL Server's native bulk-copy protocol instead of executing it as
// literal SQL text, which is 10-100x faster at GB scale: literal multi-row
// INSERT statements are capped by server-side parse/compile cost, not I/O.
//
// Parsing is strictly separated from execution: every value in the batch is
// parsed into a typed Go value, using the destination column's real SQL type
// (never guessed from literal syntax), before any driver call is made. If
// parsing fails anywhere — an unsupported type (uniqueidentifier, sql_variant,
// spatial types), or a shape we don't recognize — tryBulkInsert returns
// handled=false and the caller falls back to plain ExecContext, unchanged
// from before this existed. Once parsing succeeds, bulk copy runs against the
// real database; a failure past that point (e.g. a constraint violation) is
// reported as a genuine batch failure rather than retried, since some rows
// may have already reached the server.
func tryBulkInsert(ctx context.Context, conn *sql.Conn, cache *columnTypeCache, batch string) (handled bool, err error) {
	table, columns, rowsBlob, ok := parseInsertBatch(batch)
	if !ok {
		return false, nil
	}

	colTypes, err := cache.get(ctx, conn, table)
	if err != nil {
		return false, nil
	}

	rows, ok := parseRows(rowsBlob, columns, colTypes)
	if !ok {
		return false, nil
	}

	return true, execBulkInsert(ctx, conn, table, columns, rows)
}

func execBulkInsert(ctx context.Context, conn *sql.Conn, table string, columns []string, rows [][]any) error {
	stmt, err := conn.PrepareContext(ctx, mssql.CopyIn(table, mssql.BulkOptions{}, columns...))
	if err != nil {
		return fmt.Errorf("preparing bulk insert: %w", err)
	}
	defer stmt.Close()

	for _, row := range rows {
		if _, err := stmt.ExecContext(ctx, row...); err != nil {
			return fmt.Errorf("bulk insert row: %w", err)
		}
	}
	if _, err := stmt.ExecContext(ctx); err != nil {
		return fmt.Errorf("flushing bulk insert: %w", err)
	}
	return nil
}

// columnTypeCache memoizes each table's column->SQL-type map for the
// lifetime of one import run, so bulk copy only queries sys.columns once per
// table rather than once per batch.
type columnTypeCache struct {
	byTable map[string]map[string]string
}

func newColumnTypeCache() *columnTypeCache {
	return &columnTypeCache{byTable: map[string]map[string]string{}}
}

func (c *columnTypeCache) get(ctx context.Context, conn *sql.Conn, qualifiedTable string) (map[string]string, error) {
	if m, ok := c.byTable[qualifiedTable]; ok {
		return m, nil
	}
	schema, table, ok := splitQualifiedIdent(qualifiedTable)
	if !ok {
		return nil, fmt.Errorf("unrecognized table reference %q", qualifiedTable)
	}

	rows, err := conn.QueryContext(ctx, `
		SELECT c.name, ty.name
		FROM sys.columns c
		JOIN sys.tables t ON t.object_id = c.object_id
		JOIN sys.schemas s ON s.schema_id = t.schema_id
		JOIN sys.types ty ON c.system_type_id = ty.system_type_id AND ty.user_type_id = ty.system_type_id
		WHERE s.name = @p1 AND t.name = @p2`, schema, table)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	m := map[string]string{}
	for rows.Next() {
		var name, typ string
		if err := rows.Scan(&name, &typ); err != nil {
			return nil, err
		}
		m[name] = strings.ToLower(typ)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	c.byTable[qualifiedTable] = m
	return m, nil
}

const (
	insertPrefix = "INSERT INTO "
	valuesMarker = ") VALUES\n"
)

// parseInsertBatch recognizes exactly the shape data_gen.go generates:
//
//	INSERT INTO [schema].[table] ([Col1], [Col2]) VALUES
//	(v1, v2),
//	(v3, v4);
//
// Anything else (SET IDENTITY_INSERT, ALTER TABLE, BEGIN/COMMIT TRANSACTION,
// comments) returns ok=false so the caller uses the normal exec path.
func parseInsertBatch(batch string) (table string, columns []string, rowsBlob string, ok bool) {
	if !strings.HasPrefix(batch, insertPrefix) {
		return "", nil, "", false
	}
	rest := batch[len(insertPrefix):]

	open := strings.IndexByte(rest, '(')
	if open < 0 {
		return "", nil, "", false
	}
	table = strings.TrimSpace(rest[:open])
	rest = rest[open+1:]

	closeIdx := strings.Index(rest, valuesMarker)
	if closeIdx < 0 {
		return "", nil, "", false
	}
	colsText := rest[:closeIdx]
	rest = rest[closeIdx+len(valuesMarker):]

	if !strings.HasSuffix(rest, ";") {
		return "", nil, "", false
	}
	rowsBlob = rest[:len(rest)-1]

	for c := range strings.SplitSeq(colsText, ", ") {
		name, ok := unbracketIdent(strings.TrimSpace(c))
		if !ok {
			return "", nil, "", false
		}
		columns = append(columns, name)
	}
	return table, columns, rowsBlob, true
}

// parseRows splits rowsBlob into rows and each row into per-column values,
// parsed according to colTypes. Returns ok=false, discarding any partial
// result, the moment anything doesn't match — callers must not act on a
// partial parse.
func parseRows(rowsBlob string, columns []string, colTypes map[string]string) ([][]any, bool) {
	types := make([]string, len(columns))
	for i, col := range columns {
		t, ok := colTypes[col]
		if !ok {
			return nil, false
		}
		types[i] = t
	}

	rowChunks := splitTopLevel(rowsBlob, ',')
	rows := make([][]any, 0, len(rowChunks))
	for _, chunk := range rowChunks {
		chunk = strings.TrimSpace(chunk)
		if !strings.HasPrefix(chunk, "(") || !strings.HasSuffix(chunk, ")") {
			return nil, false
		}
		valueLits := splitTopLevel(chunk[1:len(chunk)-1], ',')
		if len(valueLits) != len(columns) {
			return nil, false
		}
		row := make([]any, len(valueLits))
		for i, lit := range valueLits {
			v, ok := parseLiteral(strings.TrimSpace(lit), types[i])
			if !ok {
				return nil, false
			}
			row[i] = v
		}
		rows = append(rows, row)
	}
	return rows, true
}

var decimalLiteralRe = regexp.MustCompile(`^-?[0-9]+(\.[0-9]+)?$`)

// parseLiteral parses one value literal exactly as sqlfmt.WriteValue could
// have produced it for colType. It never guesses: an unrecognized colType
// (uniqueidentifier, sql_variant, hierarchyid/geography/geometry, ...) always
// returns ok=false.
func parseLiteral(lit, colType string) (any, bool) {
	if lit == "NULL" {
		return nil, true
	}

	switch colType {
	case "tinyint", "smallint", "int", "bigint":
		n, err := strconv.ParseInt(lit, 10, 64)
		return n, err == nil

	case "bit":
		switch lit {
		case "0":
			return false, true
		case "1":
			return true, true
		}
		return nil, false

	case "float", "real":
		f, err := strconv.ParseFloat(lit, 64)
		return f, err == nil

	case "decimal", "numeric", "money", "smallmoney":
		if !decimalLiteralRe.MatchString(lit) {
			return nil, false
		}
		return lit, true

	// char/nchar/binary are fixed-length: SQL Server's bulk-copy protocol
	// requires the value sent for them to be exactly the column's declared
	// length, which a value round-tripped through a literal (e.g. one that
	// lost trailing pad bytes/spaces along the way) may not be. Rather than
	// try to re-derive and reproduce that padding, these fall back to plain
	// SQL text, where the server pads/truncates them itself as normal.
	case "varchar", "text", "nvarchar", "ntext", "xml":
		return unquoteLiteral(lit)

	case "date", "time", "datetime", "datetime2", "smalldatetime", "datetimeoffset":
		s, ok := unquoteLiteral(lit)
		if !ok {
			return nil, false
		}
		return parseTimeLiteral(s, colType)

	case "varbinary", "image":
		return parseHexLiteral(lit)

	default:
		return nil, false
	}
}

func unquoteLiteral(lit string) (string, bool) {
	body := lit
	if strings.HasPrefix(body, "N'") {
		body = body[1:]
	}
	if len(body) < 2 || body[0] != '\'' || body[len(body)-1] != '\'' {
		return "", false
	}
	return strings.ReplaceAll(body[1:len(body)-1], "''", "'"), true
}

func parseTimeLiteral(s, colType string) (time.Time, bool) {
	var layout string
	switch colType {
	case "date":
		layout = sqlfmt.DateLayout
	case "time":
		layout = sqlfmt.TimeLayout
	case "datetimeoffset":
		layout = sqlfmt.DateTimeOffsetLayout
	default:
		layout = sqlfmt.DateTimeLayout
	}
	t, err := time.Parse(layout, s)
	return t, err == nil
}

func parseHexLiteral(lit string) ([]byte, bool) {
	if !strings.HasPrefix(lit, "0x") {
		return nil, false
	}
	b, err := hex.DecodeString(lit[2:])
	return b, err == nil
}

// splitTopLevel splits s on sep, ignoring sep inside '...'-quoted strings
// (with ” escaping) or parenthesized sub-expressions (e.g. CONVERT(...)).
func splitTopLevel(s string, sep byte) []string {
	var parts []string
	depth := 0
	inQuote := false
	start := 0
	for i := 0; i < len(s); i++ {
		switch c := s[i]; {
		case inQuote:
			if c == '\'' {
				if i+1 < len(s) && s[i+1] == '\'' {
					i++
				} else {
					inQuote = false
				}
			}
		case c == '\'':
			inQuote = true
		case c == '(':
			depth++
		case c == ')':
			depth--
		case c == sep && depth == 0:
			parts = append(parts, s[start:i])
			start = i + 1
		}
	}
	parts = append(parts, s[start:])
	return parts
}

// splitQualifiedIdent parses "[schema].[table]" (as produced by
// sqlfmt.QuoteQualified) back into its two identifiers.
func splitQualifiedIdent(q string) (schema, table string, ok bool) {
	i := strings.Index(q, "].[")
	if i < 0 || !strings.HasPrefix(q, "[") || !strings.HasSuffix(q, "]") {
		return "", "", false
	}
	schema, ok1 := unbracketIdent(q[:i+1])
	table, ok2 := unbracketIdent(q[i+2:])
	return schema, table, ok1 && ok2
}

func unbracketIdent(s string) (string, bool) {
	if len(s) < 2 || s[0] != '[' || s[len(s)-1] != ']' {
		return "", false
	}
	return strings.ReplaceAll(s[1:len(s)-1], "]]", "]"), true
}
