//go:build integration

package integration

import (
	"bytes"
	"context"
	"database/sql"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/rafaqwe1/sqlserver-import-export/internal/export"
	"github.com/rafaqwe1/sqlserver-import-export/internal/importrun"
)

func TestExportImportRoundTrip(t *testing.T) {
	ctx := context.Background()
	srcName := newTestDatabase(t, "src")
	tgtName := newTestDatabase(t, "tgt")
	src := openDB(t, srcName)
	tgt := openDB(t, tgtName)

	execSQL(t, src, fixtureDDL()...)
	execSQL(t, src, fixtureData()...)

	dir := t.TempDir()
	// batch size 2 forces multiple INSERT statements per table, exercising batching.
	if err := export.Run(ctx, connStringForDB(srcName), dir, "", 2, 2); err != nil {
		t.Fatalf("export failed: %v", err)
	}

	schemaSQL := readFile(t, filepath.Join(dir, "schema.sql"))
	dataSQL := readFile(t, filepath.Join(dir, "data-import.sql"))

	for _, want := range []string{
		"CREATE TABLE [dbo].[Customers]",
		"CREATE TABLE [dbo].[Orders]",
		"IDENTITY(1,1)",
		"CONSTRAINT [PK_Customers] PRIMARY KEY",
		"CONSTRAINT [UQ_Customers_Email] UNIQUE",
		"CONSTRAINT [CK_Customers_Age] CHECK",
		"[TotalWithTax] AS (",
		") PERSISTED",
		"CREATE NONCLUSTERED INDEX [IX_Customers_Name]",
		"[VarcharMaxCol] varchar(MAX)",
		"[NVarcharMaxCol] nvarchar(MAX)",
		"FOREIGN KEY ([CustomerID]) REFERENCES [dbo].[Customers]",
		"FOREIGN KEY ([ManagerID]) REFERENCES [dbo].[Employees]",
		"FOREIGN KEY ([BID]) REFERENCES [dbo].[CycleB]",
		"FOREIGN KEY ([AID]) REFERENCES [dbo].[CycleA]",
		"ON DELETE CASCADE",
	} {
		if !strings.Contains(schemaSQL, want) {
			t.Errorf("schema.sql missing %q", want)
		}
	}

	for _, want := range []string{
		"NOCHECK CONSTRAINT ALL",
		"WITH CHECK CHECK CONSTRAINT ALL",
		"SET IDENTITY_INSERT [dbo].[Customers] ON",
		"SET XACT_ABORT OFF",
		"BEGIN TRANSACTION",
		"COMMIT TRANSACTION",
	} {
		if !strings.Contains(dataSQL, want) {
			t.Errorf("data-import.sql missing %q", want)
		}
	}

	if err := importrun.Run(ctx, connStringForDB(tgtName), dir, false, false); err != nil {
		t.Fatalf("import failed: %v", err)
	}

	for _, tbl := range fixtureTables() {
		srcN := rowCount(t, src, tbl)
		tgtN := rowCount(t, tgt, tbl)
		if srcN != tgtN {
			t.Errorf("%s row count mismatch: source=%d target=%d", tbl, srcN, tgtN)
		}
		if srcN == 0 {
			t.Errorf("%s: fixture produced zero rows, test is not exercising anything", tbl)
		}
	}

	assertStringEqual(t, "Customers.Notes for O'Brien",
		scalarString(t, tgt, "SELECT Notes FROM dbo.Customers WHERE Email = 'obrien@example.com'"),
		"has a quote ' in notes")

	assertStringEqual(t, "Orders.TotalWithTax recomputed on target",
		scalarString(t, tgt, "SELECT CAST(TotalWithTax AS varchar(50)) FROM dbo.Orders WHERE Amount = 100.50"),
		scalarString(t, src, "SELECT CAST(TotalWithTax AS varchar(50)) FROM dbo.Orders WHERE Amount = 100.50"))

	// Employees: manager chain must survive with identities preserved (IDENTITY_INSERT ON).
	assertStringEqual(t, "Dave's manager on target",
		scalarString(t, tgt, `SELECT m.FullName FROM dbo.Employees e JOIN dbo.Employees m ON e.ManagerID = m.EmployeeID WHERE e.FullName = N'Dave Manager'`),
		"Carol CEO")
	assertStringEqual(t, "Erin's manager on target",
		scalarString(t, tgt, `SELECT m.FullName FROM dbo.Employees e JOIN dbo.Employees m ON e.ManagerID = m.EmployeeID WHERE e.FullName = N'Erin IC'`),
		"Dave Manager")

	// Cyclic FK pair: A1 <-> B1 must reference each other after import.
	assertStringEqual(t, "CycleA.Label referenced by CycleB",
		scalarString(t, tgt, `SELECT a.Label FROM dbo.CycleA a JOIN dbo.CycleB b ON b.AID = a.AID WHERE b.Label = 'B1'`),
		"A1")
	assertStringEqual(t, "CycleB.Label referenced by CycleA",
		scalarString(t, tgt, `SELECT b.Label FROM dbo.CycleB b JOIN dbo.CycleA a ON a.BID = b.BID WHERE a.Label = 'A1'`),
		"B1")

	assertAllTypesRow(t, tgt)

	assertStringEqual(t, "LegacyTypes.TextCol",
		scalarString(t, tgt, "SELECT CAST(TextCol AS varchar(100)) FROM dbo.LegacyTypes"),
		"legacy text value")
	assertStringEqual(t, "LegacyTypes.NTextCol",
		scalarString(t, tgt, "SELECT CAST(NTextCol AS nvarchar(100)) FROM dbo.LegacyTypes"),
		"legacy ntext value")
	assertStringEqual(t, "LegacyTypes.XmlCol",
		scalarString(t, tgt, "SELECT CAST(XmlCol AS nvarchar(max)) FROM dbo.LegacyTypes"),
		"<a><b>1</b></a>")
	// RowVer must exist and be auto-generated by the target server, not copied from source.
	if !indexExists(t, tgt, "dbo", "Customers", "IX_Customers_Name") {
		t.Errorf("expected non-key index IX_Customers_Name to exist on target")
	}
}

func assertAllTypesRow(t *testing.T, tgt *sql.DB) {
	t.Helper()
	ctx := context.Background()

	row := tgt.QueryRowContext(ctx, `
		SELECT
			CAST(TinyIntCol AS varchar(10)),
			CAST(BigIntCol AS varchar(30)),
			CAST(DecimalCol AS varchar(50)),
			CAST(MoneyCol AS varchar(50)),
			VarcharCol,
			NVarcharCol,
			CAST(DateCol AS varchar(20)),
			CAST(DateTime2Col AS varchar(50)),
			CAST(GuidCol AS varchar(50)),
			BinaryCol,
			VarbinaryCol
		FROM dbo.AllTypes WHERE TinyIntCol IS NOT NULL`)

	var tinyInt, bigInt, decimalCol, moneyCol, varcharCol, nvarcharCol, dateCol, dt2Col, guidCol string
	var binaryCol, varbinaryCol []byte
	if err := row.Scan(&tinyInt, &bigInt, &decimalCol, &moneyCol, &varcharCol, &nvarcharCol, &dateCol, &dt2Col, &guidCol, &binaryCol, &varbinaryCol); err != nil {
		t.Fatalf("scanning AllTypes populated row: %v", err)
	}

	assertStringEqual(t, "AllTypes.TinyIntCol", tinyInt, "255")
	assertStringEqual(t, "AllTypes.BigIntCol", bigInt, "9223372036854775807")
	assertStringEqual(t, "AllTypes.DecimalCol", decimalCol, "12345.6789")
	assertStringEqual(t, "AllTypes.MoneyCol", moneyCol, "19999.99")
	assertStringEqual(t, "AllTypes.VarcharCol", varcharCol, `O'Brien's "quoted"`)
	assertStringEqual(t, "AllTypes.NVarcharCol", nvarcharCol, "wörld's")
	assertStringEqual(t, "AllTypes.DateCol", dateCol, "2024-03-05")
	assertStringEqual(t, "AllTypes.DateTime2Col", dt2Col, "2024-03-05 13:45:30.1234567")
	if !strings.EqualFold(guidCol, "AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE") {
		t.Errorf("AllTypes.GuidCol = %q, want (case-insensitive) AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE", guidCol)
	}

	if want := []byte{0x01, 0x02, 0x03, 0x04}; !bytes.Equal(binaryCol, want) {
		t.Errorf("AllTypes.BinaryCol = % X, want % X", binaryCol, want)
	}
	if want := []byte{0x01, 0x02, 0xFF, 0x00}; !bytes.Equal(varbinaryCol, want) {
		t.Errorf("AllTypes.VarbinaryCol = % X, want % X", varbinaryCol, want)
	}

	var nullCheck sql.NullString
	if err := tgt.QueryRowContext(ctx, "SELECT CAST(IntCol AS varchar(20)) FROM dbo.AllTypes WHERE TinyIntCol IS NULL").Scan(&nullCheck); err != nil {
		t.Fatalf("scanning AllTypes NULL row: %v", err)
	}
	if nullCheck.Valid {
		t.Errorf("expected AllTypes NULL row IntCol to be NULL, got %q", nullCheck.String)
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	return string(b)
}

func assertStringEqual(t *testing.T, what, got, want string) {
	t.Helper()
	if got != want {
		t.Errorf("%s: got %q, want %q", what, got, want)
	}
}
